In [1]:
#Task 1 — Build the Pipeline

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
data = {
    "id": list(range(1,21)),
    "title": [f"Movie {i}" for i in range(1,21)],
    "popularity": [i*5 for i in range(1,21)],
    "vote_average": [6.5 + i*0.1 for i in range(1,21)],
    "vote_count": [50 + i*10 for i in range(1,21)],
    "release_date": ["2020-01-01"]*20,
    "genre_ids": ["[28,12]","[35]","[18]","[28,53]","[16]"]*4
}

df = pd.DataFrame(data)
df.head()

   id    title  popularity  vote_average  vote_count release_date genre_ids
0   1  Movie 1           5           6.6          60   2020-01-01   [28,12]
1   2  Movie 2          10           6.7          70   2020-01-01      [35]
2   3  Movie 3          15           6.8          80   2020-01-01      [18]
3   4  Movie 4          20           6.9          90   2020-01-01   [28,53]
4   5  Movie 5          25           7.0         100   2020-01-01      [16]

In [4]:
engine = create_engine("sqlite:///:memory:")

In [5]:
df.to_sql("movies", engine, if_exists="replace", index=False)

print("Data saved to DB")

Data saved to DB

In [6]:
#Task 2 — Perform EDA

In [7]:
df = pd.read_sql("SELECT * FROM movies", engine)
df.head()

   id    title  popularity  vote_average  vote_count release_date genre_ids
0   1  Movie 1           5           6.6          60   2020-01-01   [28,12]
1   2  Movie 2          10           6.7          70   2020-01-01      [35]
2   3  Movie 3          15           6.8          80   2020-01-01      [18]
3   4  Movie 4          20           6.9          90   2020-01-01   [28,53]
4   5  Movie 5          25           7.0         100   2020-01-01      [16]

In [8]:
df.describe()

             id  popularity  vote_average  vote_count
count  20.00000   20.000000     20.000000   20.000000
mean   10.50000   52.500000      7.550000  155.000000
std     5.91608   29.580399      0.591608   59.160798
min     1.00000    5.000000      6.600000   60.000000
25%     5.75000   28.750000      7.075000  107.500000
50%    10.50000   52.500000      7.550000  155.000000
75%    15.25000   76.250000      8.025000  202.500000
max    20.00000  100.000000      8.500000  250.000000

In [9]:
import ast

df["genre_ids"] = df["genre_ids"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

genre_df = df.explode("genre_ids")

genre_df["genre_ids"].value_counts()

genre_ids
28    8
12    4
35    4
18    4
53    4
16    4
Name: count, dtype: int64

In [10]:
df.isnull().sum()

id              0
title           0
popularity      0
vote_average    0
vote_count      0
release_date    0
genre_ids       0
dtype: int64